language: node_js
node_js:
    - "7.0"
script:
    - echo "Deploying!"
install:
    - npm install -g firebase-tools
after_success:
    - firebase deploy --project srv1-fsb26-ru --token $FIREBASE_TOKEN
